name: remote test__push observe

on :
  push:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/kow21/repository_dispatch_test_b/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "send_message", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

